"""
JWT Authentication Middleware

This module provides JWT token validation and admin role checking to secure
the chatbot endpoints. It mirrors the Node.js backend's authentication logic
to ensure compatibility.

The JWT tokens are generated by the Node.js backend and contain:
- id: User ID
- email: User email
- name: User name
- (role information is embedded in the token or fetched from database)

Environment Variables Required:
- JWT_SECRET_KEY: Same secret used by the Node.js backend
"""

import os
from typing import Dict, Optional
import jwt
from jwt.exceptions import ExpiredSignatureError, InvalidTokenError
from fastapi import HTTPException, status, Header
from dotenv import load_dotenv

# Load environment variables
load_dotenv()

# Get JWT secret from environment
JWT_SECRET_KEY = os.getenv("JWT_SECRET_KEY")

if not JWT_SECRET_KEY:
    raise ValueError(
        "JWT_SECRET_KEY environment variable is required. "
        "This must match the secret used by the Node.js backend."
    )


def verify_jwt_token(token: str) -> Dict:
    """
    Verify and decode a JWT token.
    
    Args:
        token: JWT token string
        
    Returns:
        Decoded token payload containing user information
        
    Raises:
        ExpiredSignatureError: If the token has expired
        InvalidTokenError: If the token signature is invalid
    """
    try:
        # Decode and verify the token
        # algorithms=["HS256"] matches the Node.js backend's default
        payload = jwt.decode(
            token,
            JWT_SECRET_KEY,
            algorithms=["HS256"]
        )
        return payload
    except ExpiredSignatureError:
        raise ExpiredSignatureError("Token has expired")
    except InvalidTokenError as e:
        raise InvalidTokenError(f"Invalid token: {str(e)}")


def is_admin_user(payload: Dict) -> bool:
    """
    Check if the user has admin role.
    
    The Node.js backend stores role information in the database and checks
    if role_name is "admin" or "Admin" (case-insensitive).
    
    For Phase 1, we check if the payload contains role information.
    In Phase 3, this will be enhanced to query the database if needed.
    
    Args:
        payload: Decoded JWT token payload
        
    Returns:
        True if user is admin, False otherwise
    """
    # Check if role information is in the token payload
    # The exact structure depends on how the Node.js backend encodes the token
    
    # Option 1: role_name directly in payload
    role_name = payload.get("role_name") or payload.get("role", {}).get("role_name")
    
    if role_name:
        return role_name.lower() == "admin"
    
    # Option 2: Check if user object contains role
    user = payload.get("user", {})
    if isinstance(user, dict):
        user_role = user.get("role", {})
        if isinstance(user_role, dict):
            role_name = user_role.get("role_name")
            if role_name:
                return role_name.lower() == "admin"
    
    # If no role information found, assume not admin
    # In Phase 3, we'll query the database using the email from the payload
    return False


def authenticate_admin(authorization_header: Optional[str]) -> Dict:
    """
    Authenticate and verify admin user from Authorization header.
    
    This function:
    1. Extracts the JWT token from the Authorization header
    2. Verifies the token signature and expiration
    3. Checks if the user has admin role
    4. Returns the decoded payload if all checks pass
    
    Args:
        authorization_header: Authorization header value (e.g., "Bearer <token>")
        
    Returns:
        Decoded token payload if authentication succeeds
        
    Raises:
        HTTPException: If authentication fails (401 Unauthorized)
    """
    # Check if Authorization header is present
    if not authorization_header:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Authorization header is required"
        )
    
    # Extract token from "Bearer <token>" format
    parts = authorization_header.split()
    
    if len(parts) != 2 or parts[0].lower() != "bearer":
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Invalid Authorization header format. Expected: Bearer <token>"
        )
    
    token = parts[1]
    
    # Verify the token
    try:
        payload = verify_jwt_token(token)
    except ExpiredSignatureError:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Token has expired"
        )
    except InvalidTokenError as e:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail=f"Invalid token: {str(e)}"
        )
    
    # Check if user is admin
    if not is_admin_user(payload):
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail="Admin access required"
        )
    
    return payload


# FastAPI dependency for protecting endpoints
from fastapi import Header

def get_current_admin_user(authorization: Optional[str] = Header(None)) -> Dict:
    """
    FastAPI dependency to get the current authenticated admin user.
    
    Usage in FastAPI routes:
        @app.get("/admin/endpoint")
        async def protected_endpoint(
            user: Dict = Depends(get_current_admin_user)
        ):
            # user contains the decoded JWT payload
            return {"message": "Admin access granted"}
    
    Args:
        authorization: Authorization header value (injected by FastAPI)
        
    Returns:
        Decoded token payload
        
    Raises:
        HTTPException: If authentication fails
    """
    return authenticate_admin(authorization)


__all__ = [
    "verify_jwt_token",
    "is_admin_user",
    "authenticate_admin",
    "get_current_admin_user"
]
